Complete refactoring of task list service and persistency of Task List
SCS-ASSE-FS21-Group3/tapas pull request #37
Opened 2021-12-11 20:53 UTC by rbngz

Hello @gianlucafrei 
This PR contains a large refactoring of the Task List Service. I completely deleted the `TaskList` domain object and implemented complete all around persistency of Tasks.

2021-12-11 21:56 UTC, rbngz commented
The second part of this PR implements the persistency of the executor pool. Here we only store the static information of the executors to the MongoDB database (E.g., name, id, type..).
When the service is started, the executors are retrieved from the db and stored within the internal repository. This will be used to track assignment of tasks, current state of the executor, etc.) and will be lost once the service stops. (In-memory)

2021-12-11 22:09 UTC, rbngz commented
Sorry, forgot to fix the tests. Will do tomorrow evening. Let me know if you want to fix them instead

2021-12-12 12:44 UTC, gianlucafrei commented
The tests in the executor pool seem to require the real mongo db. Those tests should run locally without any dependencies.

2021-12-12 12:51 UTC, gianlucafrei requested changes

2021-12-12 12:51 UTC, gianlucafrei commented on tapas-executor-pool/src/main/java/ch/unisg/tapasexecutorpool/pool/adapter/out/persistence/mongodb/ExecutorMapper.java
> +@Component
Does this class really need to be a bean? I'll add this functionality to the MongoTaskDocument class.

2021-12-12 12:51 UTC, gianlucafrei commented on tapas-executor-pool/src/main/java/ch/unisg/tapasexecutorpool/pool/adapter/out/persistence/mongodb/ExecutorPersistenceAdapter.java
> +    @Autowired
Autowired should no be mixed with constructor injection. Just use one of the two methods for DI.

2021-12-12 12:51 UTC, gianlucafrei commented on tapas-tasks/src/main/java/ch/unisg/tapastasks/tasks/application/service/NoOpTaskListLock.java
>          //do nothing
I don't understand this. Why is there a NoOp Lock here.

2021-12-12 12:52 UTC, gianlucafrei commented
Overall seems really a good refactoring, please just address those minor changes.

2021-12-12 19:36 UTC, rbngz commented on tapas-tasks/src/main/java/ch/unisg/tapastasks/tasks/application/service/NoOpTaskListLock.java
>          //do nothing
I wish I would understand this. This file is taken from the tutors repository (See [here](https://github.com/SCS-ASSE-FS21-Tutors/tapas/blob/main/tapas-tasks/src/main/java/ch/unisg/tapastasks/tasks/application/service/NoOpTaskListLock.java)). I thought I just slightly modify this implementation.

2021-12-12 19:48 UTC, rbngz commented on tapas-executor-pool/src/main/java/ch/unisg/tapasexecutorpool/pool/adapter/out/persistence/mongodb/ExecutorMapper.java
> +@Component
I did get my inspiration  from the example implementation of the task list persistency. I think it also makes sense to separate this functionality, given our overall granularity and this illustration from the slide decks.
<img width="645" alt="Screenshot 2021-12-12 at 20 46 26" src="https://user-images.githubusercontent.com/28656856/145727180-4a8852a3-10d4-460a-a18e-e509744b8654.png">

2021-12-13 09:30 UTC, gianlucafrei commented on tapas-executor-pool/src/main/java/ch/unisg/tapasexecutorpool/pool/adapter/out/persistence/mongodb/ExecutorMapper.java
> +@Component
Ok agre on the separation part. But does not need to be a bean. Just instantiate it in the Repository class with the constructor. But not a big concern.

2021-12-13 10:57 UTC, merged